# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_articles_filesystem
                cache_prefix: media/cache
                root_url: "%articles_upload_url%"
    # default cache resolver for saving thumbnails
    cache: flysystem_resolver
    filter_sets:
        cache: ~
        # the name of the "filter set"
        articles:
            quality: 90
            filters:
                thumbnail: { size: [250, 250], mode: outbound }
    loaders:
        articles_flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_articles_filesystem
    # default loader to use for all filter sets
    data_loader: articles_flysystem_loader
