oneup_flysystem:
    adapters:
        uploads_articles_adapter:
            local:
                location: '%kernel.project_dir%/public/%articles_upload%'
    filesystems:
        uploads_articles:
            adapter: uploads_articles_adapter
